### ISSUE TITLE
libonig problem regexec

### ISSUE THREAD

**Issue by BenMitnicK** [TheOfficialFloW/VitaShell#169]
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/lib\libonig.a(regcomp.o): In function `disable_noname_group_capture':
regcomp.c:(.text+0x1a08): undefined reference to `alloca'
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/6.2.0/../../../../arm-vita-eabi/lib\libonig.a(regexec.o): In function `match_at':
regexec.c:(.text+0xc52): undefined reference to `alloca'
regexec.c:(.text+0x2d0c): undefined reference to `alloca'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:52: VitaShell.elf] Error 1

I don't understand why compile with version 5.9.6 and 6.0.0 it's same libonig.a not reconized please help

**Comment by TheOfficialFloW** [comment]
Using the latest vitasdk vdpm should resolve this.

**Comment by BenMitnicK** [comment]
Yes but I solved with Linux version :) thx
